### ISSUE TITLE
Localization via hard link has failed

### ISSUE THREAD

**Issue by fangpingmu** [ENCODE-DCC/caper#37]
Cromwell seems to love hard-links. Due to security reasons, hard links are not supported in many network mounts and virtual environments.

caper uses hard link by default. How can I change the configuration file to use soft link?

**Comment by leepc12** [comment]
For localization if hard-linking fails, Cromwell automatically tries other strategies like soft-linking/copying. You can simply ignore any warnings that Cromwell spit out.

However, this is for localization only. Cromwell always hard-links when globbing outputs of each task (`glob-*` directories under `execution`). There has been some issues with BeeGFS filesystem which does not allow hard-linking. This is a known issue of Cromwell and can't be fixed in Caper's side.
